{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-keycloak-config
  labels:
    {{- include "keycloak-config-cli.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak-config
data:
  config.yaml: |
    {{- $realmConfig := dict "realm" (.Values.realm | default .Values.config.realm | default "company") -}}
    {{- range $k, $v := .Values -}}
      {{- if not (has $k (list "appName" "enabled" "image" "keycloak" "config" "job" "serviceAccount" "nameOverride" "fullnameOverride")) -}}
        {{- $_ := set $realmConfig $k $v -}}
      {{- end -}}
    {{- end -}}
    {{- toYaml $realmConfig | nindent 4 }}
{{- end }}
